const ENTITY_TYPES = {
    WORKSPACE: 'WORKSPACE',
    BOARD: 'BOARD',
    SECTION: 'SECTION',
    COLUMN: 'COLUMN',
    COLUMN_RESTRICTION: 'COLUMN_RESTRICTION',
    ITEM: 'ITEM',
    ITEM_VALUE: 'ITEM_VALUE',
    ITEM_UPDATE: 'ITEM_UPDATE',
    COMMENT: 'COMMENT',
    MEMBER: 'MEMBER',
    ITEM_ASSIGNEE: 'ITEM_ASSIGNEE',
}

module.exports = ENTITY_TYPES