const NOTIFICATION_TYPES = {
    ITEM_CREATED: 'ITEM_CREATED',
    ITEM_UPDATED: 'ITEM_UPDATED',
    ITEM_DELETED: 'ITEM_DELETED',
    ITEM_MOVED: 'ITEM_MOVED',
    COMMENT_CREATED: 'COMMENT_CREATED',
    COMMENT_UPDATED: 'COMMENT_UPDATED',
    COMMENT_DELETED: 'COMMENT_DELETED',
}

module.exports = {
    NOTIFICATION_TYPES
}