const NOTIFICATION_TYPES = {
    ITEM_CREATED: 'ITEM_CREATED',
    ITEM_UPDATED: 'ITEM_UPDATED',
    ITEM_DELETED: 'ITEM_DELETED',
    ITEM_MOVED: 'ITEM_MOVED',
    COMMENT_ADDED: 'COMMENT_ADDED'
}

module.exports = {
    NOTIFICATION_TYPES
}